function B = plotCoeffLinearModel_v2( ...
    param_table ...
)
% takes a fitted linear model lm and displays the coefficients as a bar
% chart, along with confidence intervals and color coding for p-values. The
% order of the color code is in order of increasing significance.

%%

% get colors based on significance level
param_table.significance_color = signifColorCode( ...
    param_table.p_values, ...
    ["lime", "yellow", "orange", "red"] ...
    );

n_param = height(param_table);

B = bar( ...
    param_table.coef, ...
    "BarWidth", 0.05, ...
    "FaceColor", color2triplet("grey"), ...
    "EdgeColor", "none");
set(gca, ...
    'xtick', 1:n_param, ...
    'XTickLabel', param_table.Properties.RowNames, ...
    'TickLabelInterpreter', 'latex')

plotCIforEachCat(1:n_param, ...
    param_table{:, ["ci_lower", "ci_upper"]}', ...
    param_table{:, "significance_color"})

end