names_map = [; ...
    ["sex_1", "male"]; ...
    ["friendsSupp_0", "no friend support"]; ...
    ["bmi_1", "BMI under"]; ...
    ["bmi_2", "BMI normal"]; ...
    ["bmi_4", "BMI obese"]; ...
    ["highBP_1", "high BP"]; ...
    ["smokeNow_1", "current smoker"]; ...
    ["old_1:PAf4i3_1", "old:PAf4i3"]; ...
    ["old_1:bmi_1", "old:BMI under"]; ...
    ["diabHba1c_1", "diabetes"]; ...
    ["old_1:bmi_2", "old:BMI normal"]; ...
    ["old_1:bmi_4", "old:BMI obese"]; ...
    ["education_1", "education lvl 1"]; ...
    ["education_2", "education lvl 2"]; ...
    ["PA_f1i1", "PAf1i1"]; ...
    ["PA_f1i2", "PAf1i2"]; ...
    ["PA_f1i3", "PAf1i3"]; ...
    ["PA_f2i1", "PAf2i1"]; ...
    ["PA_f2i2", "PAf2i2"]; ...
    ["PA_f2i3", "PAf2i3"]; ...
    ["PA_f3i1", "PAf3i1"]; ...
    ["PA_f3i3", "PAf3i3"]; ...
    ["PA_f4i1", "PAf4i1"]; ...
    ["PA_f4i2", "PAf4i2"]; ...
    ["PA_f4i3", "PAf4i3"]; ...
    ["age^2", "age$^2$"]; ...
    ["hii^2", "HII$^2$"]; ...
    ["hscl^2", "HSCL$^2$"]; ...
    ["hscl^3", "HSCL$^3$"]];