function effect_table = get_PA_effects_relative_to_ref_group( ...
    lme, ...
    group, ...
    ref_group ...
    )
% Computes effect of PA on SRH relative to reference group. Computes
% confidence intervals and p-values in relation to the reference group.
%%
% Extract info
[ci, SD_effect] = util_get_CI_for_paramDiff(lme, group, ref_group);
effect_table.coef = ci(1);
effect_table.ci_lower = ci(2);
effect_table.ci_upper = ci(3);
effect_table.p_values = 2 * (1 - normcdf(abs(effect_table.coef)/SD_effect));

effect_table = struct2table( ...
    effect_table, ...
    "RowNames", group ...
    );

end