% This array serves 3 purposes. 1) It informs which variables are to be
% discarded, 2) it informs the order in which the variables whould be
% presented (if a variable does not appear in the left column, it will not
% be plotted), 3) it informs how the variables whould be renames.
function names_map = get_array_for_renaming_and_reordering_variables()
    names_map = [; ...
        % Demographics
        ["age^2", "age$^2$"]
        ["age=40", "Age=40"]
        ["age=50", "Age=50"]; ...
        ["age=70", "Age=70"]; ...
        ["sex_1", "Male"]; ...
        ["education_1", "Upper secondary education"]; ...
        ["education_2", "High school diploma"]; ...
        % HII
        ["hii", "HII"]; ...
        ["hii^2", "HII^2"]; ...
        ["HII=2", "HII=2"]; ...
        ["HII=4", "HII=4"]; ...
        ["HII=6", "HII=6"]; ...
        % BMI
%         ["bmi_1", "BMI under"]; ...
        ["bmi_2", "BMI normal"]; ...
        ["bmi_4", "BMI obese"]; ...
        % Blood pressure
        ["highBP_1", "High BP"]; ...
        % Diabetes
        ["diabHba1c_1", "Diabetes"]; ...
        % Smoking
        ["smokeNow_1", "Current smoker"]; ...
        % Exercise
        ["PA_f1i1", "Mild PA<1/week"]; ...
        ["PA_f2i1", "Mild PA 1/week"]; ...
        ["PA_f3i1", "Mild PA 2-3/week"]; ...
        ["PA_f4i1", "Mild PA$\geq$4/week"]; ...

        ["PA_f1i2", "Moderate PA$<$1/week"]; ...
        ["PA_f2i2", "Moderate PA 1/week"]; ...
        ["PA_f3i2", "Moderate PA 2-3/week"]; ...
        ["PA_f4i2", "Moderate PA$\geq$4/week"]; ...
        
        ["PA_f1i3", "Intense PA$<$1/week"]; ...
        ["PA_f2i3", "Intense PA 1/week"]; ...
        ["PA_f3i3", "Intense PA 2-3/week"]; ...
        ["PA_f4i3", "Intense PA$\geq$4/week"]; ...
        % HSCL
        ["hscl", "HSCL"]; ...
        ["hscl^2", "HSCL^2"]; ...
        ["hscl^3", "HSCL^3"]; ...
        ["HSCL=2", "HSCL=2"]; ...
        ["HSCL=3", "HSCL=3"]; ...
        ["HSCL=4", "HSCL=4"]; ...
        % Friend support
        ["friendsSupp_0", "Lack friend support"]; ...
        % Interactions
        ["old_1:PAf4i3_1", "Age$>$65:intense PA$\geq$4/week"]; ...
        ["old_1:bmi_2", "Age$>$65:BMI normal"]; ...
        ["old_1:bmi_4", "Age$>$65:BMI obese"]; ...
    ];
end