function mu_bmi = probJunkFood(S)
PA  = S.exercise;
junkFood = S.junkFood; 
mentIll = S.mentIll;
insomnia = S.insomnia;
srh = S.srh;

mu_bmi = .3 ...
    - PA(end)*.2 - PA(end-1)*.3 - PA(end-3)*0.2 - mean(PA(end-14:end-7))*.3...
    + mentIll(end)*0.8 + mentIll(end-1)*.0 + mean(mentIll(end-14:end-7))*.0...
    + junkFood(end)*0.5 ...
    + insomnia(end)*.9+ insomnia(end-1)*.1 + + mean(insomnia(end-14:end-7))*.1...
    - srh(end)*.0;
end