function mu_SRH = probSRH(S)
PA  = S.exercise;
junkFood = S.junkFood; 
mentIll = S.mentIll;
insomnia = S.insomnia;
srh = S.srh;
mu_SRH = .2 ...
    + PA(end)*1.7 + PA(end-1)*0.8 + PA(end-3)*0.45 + mean(PA(end-14:end-7))*0.5 ...
    - mentIll(end)*1.1 ...
    - junkFood(end)*0.4 - junkFood(end)*0.3 - mean(junkFood(end-14:end-7))*0.2 ...
    - insomnia(end)*1.6 - insomnia(end-1)*.4 - insomnia(end-2)*.2 ...
    + srh(end)*1;
end