% Here I check the predefined highBP variable to see if it agrees with
% cutoff values on the internet.

I_highBP_raw = myor({ ...
    compare(TUdata0.MEAN_SYSBP_T, ">", 120), ...
    compare(TUdata0.MEAN_DIABP_T6, ">", 80), ...
    compare(TUdata0.BP_TREATMENT_T6, "==", 1), ...
    }, "and");

I_highBP_predef_t6 = compare(TUdata0.highBP, ">=",  1);

% Inan = or(isnan(I_highBP_predef_t6), isnan(I_highBP_raw_t6))
% t = and(TUdata0.time == 6, ~Inan);
t = and(TUdata0.time == 6, ~isnan(TUdata0.hypertension));
% I_agreement = I_highBP_raw_t6 == I_highBP_predef_t6;
I_agreement = I_highBP_raw == TUdata0.hypertension;
mean(I_highBP_raw(t) == TUdata0.hypertension(t))

I_disagree_t6 = and(~I_agreement, TUdata0.time == 6)
T = array2table([
    TUdata0.MEAN_SYSBP_T(I_disagree_t6), ...
    TUdata0.MEAN_DIABP_T6(I_disagree_t6), ...
    TUdata0.BP_TREATMENT_T6(I_disagree_t6), ...
    I_highBP_raw(I_disagree_t6), ...
    TUdata0.hypertension(I_disagree_t6), ...
    TUdata0.highBP(I_disagree_t6)
], ...
"VariableNames", ...
["systolic", "diastolic", "BP-lowering medicine", "raw", "hypertension", "high BP"])

%%

mean(I_highBP_raw(t) == I_highBP_predef_t6(t))
mean(I_highBP_raw(t) == TUdata0.hypertension(t))