function highBP = gen_highBP(TUdata0)
% Generate high bloodpressure variable from mean systolic and diastolic
% bloodpressure using cutoff values.
%%
highBP = myor({ ...
    compare(TUdata0.MEAN_SYSBP_T, ">", 140), ...
    compare(TUdata0.MEAN_DIABP_T6, ">", 90) ...
    }, "and");

highBP_t7 = myor({ ...
    compare(TUdata0.MEAN_SYSBP_T, ">", 140), ...
    compare(TUdata0.MEAN_DIABP_T7, ">", 90) ...
    }, "and");

highBP(TUdata0.time==7) = highBP_t7(TUdata0.time==7);

end